name: uni_translate_client
description: A universal translate client.
version: 0.0.1
homepage: https://github.com/biyidev/uni_translate/tree/main/packages/uni_translate_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.0.0
